export const SET_DIALOGS_CHART_DATA = 'SET_DIALOGS_CHART_DATA';
export const SET_DAYS_CHART_DATA = 'SET_DAYS_CHART_DATA';
export const SET_WEEKS_CHART_DATA = 'SET_WEEKS_CHART_DATA';
export const SET_MONTHS_CHART_DATA = 'SET_MONTHS_CHART_DATA';
export const SET_YEARS_CHART_DATA = 'SET_YEARS_CHART_DATA';
export const SET_SELECTED_DATES = 'SET_SELECTED_DATES';
export const SET_INDEX_OF_LAST_DISPLAYED_ITEM = 'SET_INDEX_OF_LAST_DISPLAYED_ITEM';
export const SET_SENTIMENT_DATA = 'SET_SENTIMENT_DATA';
export const SET_ART_DATA = 'SET_ART_DATA';
export const SET_FRT_DATA = 'SET_FRT_DATA';
export const SET_LABELS_DATA = 'SET_LABELS_DATA';
export const SET_IS_FETCHING = 'SET_IS_FETCHING';
export const SET_SELECTED_ONE_DATE = 'SET_SELECTED_ONE_DATE';
export const SET_CSAT_DATA = 'SET_CSAT_DATA';






